// Code generated by qtc from "client_add_tools.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line client_add_tools.qtpl:1
package codegen

//line client_add_tools.qtpl:1
import "github.com/grokify/mogo/text/stringcase"

//line client_add_tools.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line client_add_tools.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line client_add_tools.qtpl:2
func StreamClientAddTools(qw422016 *qt422016.Writer, objs []stringcase.CaserNoun) {
//line client_add_tools.qtpl:2
	qw422016.N().S(`
package tools

import "github.com/modelcontextprotocol/go-sdk/mcp"

func (tc *ToolsClient) AddTools(svr *mcp.Server) {
	mcp.AddTool(svr, GetIdeaTool(), tc.GetIdea)
	`)
//line client_add_tools.qtpl:9
	for _, obj := range objs {
//line client_add_tools.qtpl:9
		qw422016.N().S(`
	mcp.AddTool(svr, Get`)
//line client_add_tools.qtpl:10
		qw422016.E().S(obj.Singular.PascalCase())
//line client_add_tools.qtpl:10
		qw422016.N().S(`Tool(), tc.Get`)
//line client_add_tools.qtpl:10
		qw422016.E().S(obj.Singular.PascalCase())
//line client_add_tools.qtpl:10
		qw422016.N().S(`)`)
//line client_add_tools.qtpl:10
	}
//line client_add_tools.qtpl:10
	qw422016.N().S(`
}

`)
//line client_add_tools.qtpl:13
}

//line client_add_tools.qtpl:13
func WriteClientAddTools(qq422016 qtio422016.Writer, objs []stringcase.CaserNoun) {
//line client_add_tools.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line client_add_tools.qtpl:13
	StreamClientAddTools(qw422016, objs)
//line client_add_tools.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line client_add_tools.qtpl:13
}

//line client_add_tools.qtpl:13
func ClientAddTools(objs []stringcase.CaserNoun) string {
//line client_add_tools.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line client_add_tools.qtpl:13
	WriteClientAddTools(qb422016, objs)
//line client_add_tools.qtpl:13
	qs422016 := string(qb422016.B)
//line client_add_tools.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line client_add_tools.qtpl:13
	return qs422016
//line client_add_tools.qtpl:13
}
