// Code generated by qtc from "tools_markdown.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line tools_markdown.qtpl:1
package codegen

//line tools_markdown.qtpl:1
import "strings"

//line tools_markdown.qtpl:2
import "github.com/grokify/mogo/text/stringcase"

//line tools_markdown.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tools_markdown.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tools_markdown.qtpl:3
func StreamToolsMarkdown(qw422016 *qt422016.Writer, objs []stringcase.CaserNoun) {
//line tools_markdown.qtpl:3
	qw422016.N().S(`
`)
//line tools_markdown.qtpl:4
	for _, obj := range objs {
//line tools_markdown.qtpl:4
		qw422016.N().S(`
1. [ ] `)
//line tools_markdown.qtpl:5
		qw422016.E().S(obj.Plural.Display())
//line tools_markdown.qtpl:5
		qw422016.N().S(`
    - [x] `)
//line tools_markdown.qtpl:5
		qw422016.N().S("`")
//line tools_markdown.qtpl:5
		qw422016.N().S(`get_`)
//line tools_markdown.qtpl:6
		qw422016.E().S(obj.Singular.SnakeCase())
//line tools_markdown.qtpl:6
		qw422016.N().S(``)
//line tools_markdown.qtpl:6
		qw422016.N().S("`")
//line tools_markdown.qtpl:6
		qw422016.N().S(`: Get a specific `)
//line tools_markdown.qtpl:6
		qw422016.E().S(strings.ToLower(obj.Singular.Display()))
//line tools_markdown.qtpl:6
	}
//line tools_markdown.qtpl:6
	qw422016.N().S(`
`)
//line tools_markdown.qtpl:7
}

//line tools_markdown.qtpl:7
func WriteToolsMarkdown(qq422016 qtio422016.Writer, objs []stringcase.CaserNoun) {
//line tools_markdown.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tools_markdown.qtpl:7
	StreamToolsMarkdown(qw422016, objs)
//line tools_markdown.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line tools_markdown.qtpl:7
}

//line tools_markdown.qtpl:7
func ToolsMarkdown(objs []stringcase.CaserNoun) string {
//line tools_markdown.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line tools_markdown.qtpl:7
	WriteToolsMarkdown(qb422016, objs)
//line tools_markdown.qtpl:7
	qs422016 := string(qb422016.B)
//line tools_markdown.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line tools_markdown.qtpl:7
	return qs422016
//line tools_markdown.qtpl:7
}
